### PR TITLE
Format fstab and add F2FS support

### PR DESCRIPTION
**Pull request by TheSync**
* Actually there is no problem with this fstab, it's just a little less pleasing to the eye.

* Because LOS now has become pure FBE
  which applies to changes: https://github.com/Dhina17/android_device_xiaomi_onclite/commit/a5f4622b1f647b98eae476a9729452ba2b70322e
  so can add F2FS support to the fstab, so that users can boot and work properly.

### CODE REVIEW

**Comment by TheSync** [comment]
* Also F2FS support has been added to the boardconfig configuration
  this is defined on the line: https://github.com/Dhina17/android_device_xiaomi_onclite/blob/9d9c4ef4253b4afffa6ccd9013c02c962430f116/BoardConfig.mk#L139

* However, fstab configuration has not been determined

**Comment by Dhina17** [comment]
>     * Actually there is no problem with this fstab, it's just a little less pleasing to the eye.
> 
>     * Because LOS now has become pure FBE
>       which applies to changes: [a5f4622](https://github.com/Dhina17/android_device_xiaomi_onclite/commit/a5f4622b1f647b98eae476a9729452ba2b70322e)
>       so can add F2FS support to the fstab, so that users can boot and work properly.

No I can't drop the FDE support from LOS side. I abandoned the patch( https://review.lineageos.org/c/LineageOS/android_device_xiaomi_onclite/+/292683 ) .

**Comment by Dhina17** [comment]
>     * Also F2FS support has been added to the boardconfig configuration
>       this is defined on the line: https://github.com/Dhina17/android_device_xiaomi_onclite/blob/9d9c4ef4253b4afffa6ccd9013c02c962430f116/BoardConfig.mk#L139
> 
>     * However, fstab configuration has not been determined

yep it will be removed. useless there. I can't move to ext4 to f2fs in mid of the shipping device

**Comment by TheSync** [comment]
Well so, they don't approve of that

**Pull request closed without merging**
